### ISSUE TITLE
The Gazebo environment just show an empty world with a quacopter only

### ISSUE THREAD

**Issue by ibrahimqazi** [pulver22/ardrone_tf_controller#2]
Hi there!
I want to this simulation but first problem is it takes a lot of time to load and second problem that after loading there an empty world with a single quadrotor only, nothing else is on the display. What could be the possible reason for this. Thanks

**Comment by pulver22** [comment]
Hi @ibrahimqazi,

can you provide me the exact command you are typing in the console? 

Gazebo should take time to load only the first time, because it must connect to the remote repository in order to download all the models.

**Comment by ibrahimqazi** [comment]
I tried both these commands, 
`roslaunch deep_reinforced_landing drl.launch`
`roslaunch qlab_gazebo qlab.launch`
but the window appears for both is same. So approximately how much do I need to wait? Because I waited for about 5 minutes in each case.   Thanks

**Comment by ibrahimqazi** [comment]
This time I waited for more than 30 minutes but still the same window with no changes. Do I need to add repository addresses to my Ubuntu **Software & Updates** list ? if yes then how can I do that and what are the addresses? Please

**Comment by pulver22** [comment]
Hi @ibrahimqazi,

> This time I waited for more than 30 minutes but still the same window with no changes. Do I need to add repository addresses to my Ubuntu **Software & Updates** list ? if yes then how can I do that and what are the addresses? Please

No, you don't have to add anything to your Updates list.




> I tried both these commands,
> `roslaunch deep_reinforced_landing drl.launch`
> `roslaunch qlab_gazebo qlab.launch`
> but the window appears for both is same. So approximately how much do I need to wait? Because I waited for about 5 minutes in each case. Thanks

These two commands are not referred to this repository but to [QLAB](https://github.com/pulver22/QLAB) instead. Therefore, I must close the issue. Be free to open it again in the correct repository. In any case, it's correct that in that case the windows that appear should be empty with only the drone and, eventually, the landing marker.
